In [1]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig
import pandas as pd

A = array([[1,2.9],
           [0.6,0.2],
           [2.2,2.9],
           [1.4,3.1],
           [3,3.0],
           [2,2.8],
           [2,1.6],
           [1,2.1],
           [1,1.6],
           [1.1,0.9]])
print(A)

[[1.  2.9]
 [0.6 0.2]
 [2.2 2.9]
 [1.4 3.1]
 [3.  3. ]
 [2.  2.8]
 [2.  1.6]
 [1.  2.1]
 [1.  1.6]
 [1.1 0.9]]


In [2]:
M = mean(A.T, axis=1)
print(M)

[1.53 2.11]


In [3]:
C = A - M
print(C)

[[-0.53  0.79]
 [-0.93 -1.91]
 [ 0.67  0.79]
 [-0.13  0.99]
 [ 1.47  0.89]
 [ 0.47  0.69]
 [ 0.47 -0.51]
 [-0.53 -0.01]
 [-0.53 -0.51]
 [-0.43 -1.21]]


In [4]:
V = cov(C.T)
print(V)

[[0.55122222 0.43855556]
 [0.43855556 1.01433333]]


In [5]:

values, vectors = eig(V)
print(vectors)
print(values)


[[-0.85641973 -0.5162802 ]
 [ 0.5162802  -0.85641973]]
[0.28684537 1.27871018]


In [6]:
P = vectors.T.dot(C.T)
print(P.T)

[[ 0.86176382 -0.40294308]
 [-0.18962483  2.11590227]
 [-0.16593986 -1.02247932]
 [ 0.62245196 -0.78073911]
 [-0.79944762 -1.52114546]
 [-0.04628393 -0.83358131]
 [-0.66582018  0.19412237]
 [ 0.44873965  0.2821927 ]
 [ 0.19059955  0.71040257]
 [-0.25643856  1.25826836]]


In [7]:
from sklearn.decomposition import PCA

pca = PCA(2)
pca.fit_transform(A)
print(pca.components_)
print(pca.explained_variance_)

B = pca.transform(A)
print(B)


[[-0.5162802  -0.85641973]
 [-0.85641973  0.5162802 ]]
[1.27871018 0.28684537]
[[-0.40294308  0.86176382]
 [ 2.11590227 -0.18962483]
 [-1.02247932 -0.16593986]
 [-0.78073911  0.62245196]
 [-1.52114546 -0.79944762]
 [-0.83358131 -0.04628393]
 [ 0.19412237 -0.66582018]
 [ 0.2821927   0.44873965]
 [ 0.71040257  0.19059955]
 [ 1.25826836 -0.25643856]]
